### ISSUE TITLE
Barcode Scanning Update

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1015]
ITS-Pro time tracking: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] Client-side, the scanning feature checks that either a Student ID, Employee ID, or Account ID exists before confirming a success, in addition to the current barcode value check
- [x] Server-side, the scanning feature checks that either a Student ID, Employee ID, or Account ID exists before confirming a success, in addition to the current barcode value check
- [x] Sync QA JSON response to Prod JSON reponse

Note: implement both server and client side check (if feasible)

**Comment by gmihir** [comment]
Implemented on qa/webview/mihir-test , passes my initial testing. Need to move to QA and test with ScanData itself to verify.

**Moving this from a QA environment to PROD is more involved than the current migration process since the QA and PROD ScanData API return different JSONs with different keys.** I have added some in-line documentation to clarify this.

**Comment by gmihir** [comment]
Updated QA and pushed to sourcecode (master branch)
