### ISSUE TITLE
Parking Lot Data

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1023]
ITS-Pro time category: https://its-pro.ucsd.edu/projects/MA/issues/MA-34?filter=allopenissues

This is complete when:

- [x] The available spots for Sixth College and Pepper Canyon is correct, currently showing "08002" spots available
- [x] The available spots for Moores Cancer Center is correct, currently showing "078018" spots available
- [x] Other lot location is verified for correct data

**Comment by a6wu** [comment]
![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/ecee5222-94d2-4787-b62a-85962ea831db)

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/7ef60500-b54c-4ae8-8e7e-39b7893de747)

**Comment by a6wu** [comment]
With "Staff/Graduate Students" and "Faculty and Senior Staff" toggle on for parking spot types, Sixth College and Pepper Canyon displays: "080" spots available.Moores Cancer Center displays "078" available.

![image.png](https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/1b455ffe-871e-44b9-85a7-ae4428eb7073)

**Comment by lukedutta9** [comment]
Update for the total spots in the screenshot below.

There's three spots where code needs to be changed:

1. Added new variable openSpacesForThisSelection. Previously, the parking card was just showing the total spots for each parking area. Now, we'll have another variable so that user's can also see a numerical value for the available parking spots.

```javascript
var totalSpacesForThisSelection = 0;
var openSpacesForThisSelection = 0;
var numSpotsSelected = 0;
```

2. In the code block where we are getting the data from query string, added incrementation for openSpacesForThisSelection and made sure that a integer is being added, not a String. For the two parking lots listed above (and possibly more), their values for number of parking spots is represented as a String, not an int like other lots in the API. So the simple fix is just to parseInt.

```javascript
// Get data (text and color) for spot types from query string
var userSpotData = {};
if (spotsQuery != undefined) {
    const selectedSpotsFromQuery = spotsQuery.split(",");
    for (var i = 0; i <= 2; i++) {
        const selected = selectedSpotsFromQuery[i];
        if (selected) {
            const thisSpotData = makeSpotData(selected, availability);
            userSpotData[selected] = thisSpotData;
            totalSpacesForThisSelection += parseInt(thisSpotData["total"]);
            openSpacesForThisSelection += parseInt(thisSpotData["open"]);
            numSpotsSelected++;
        }
    }
}
```

3. Changed where HTML was edited to account for open spots.

```javascript
document.getElementById(
    "total_spots"
).innerHTML = `~ ${openSpacesForThisSelection} 
    of ${totalSpacesForThisSelection} Spots Available`;
```

![Screen Shot 2020-10-22 at 10.07.31 AM.png](https://images.zenhubusercontent.com/5ed06a8f9b11fd221d012097/e3808ac4-d7ad-4a03-9b8c-52e52ec18ded)
