### ISSUE TITLE
Bug: Android Barcode Scanner

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1100]
User report:

My Andriod worked with the update until the screen went to sleep. After unlocking it, the scanner app was black. I for quit the UC San Diego App and it didn't solve it. Reboot phone and now it works like a champ (even if the screen locks and I unlock it. Android 10, UCSD Protected, Moto Z4

**Comment by gmihir** [comment]
Unable to replicate issue with native scanner on Samsung Galaxy S7. Tried to replicate multiple times, every time the device went to sleep and was then unlocked, scanner showed the camera view as expected. Looked through the code and I can't find a reason for this behavior to exist, it's possible it may be confusing for users since the splash screen for Android is a black screen.

When waking up device into the UCSD app, a black screen is visible while the application is loading (this is really the nonexistent splash screen). This does seem like the app has crashed/stopped to work. For now, this behavior is not able to be replicated.
