### ISSUE TITLE
Support Analytics Label for Push Notifications

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1112]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-60

This is complete when:
- [x] Analytics label are added to each push notifications sent
- [x] Testing PASS in QA
- [x] Deployed to PROD (@a6wu)
- [x] Testing PASS in PROD

Reference: https://firebase.google.com/docs/cloud-messaging/understand-delivery?authuser=0#adding-analytics-labels-to-messages

**Comment by g9singh** [comment]
From the docs [here](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages?authuser=0#AndroidFcmOptions) and [here](https://firebase.google.com/docs/cloud-messaging/understand-delivery?authuser=0#adding-analytics-labels-to-messages) it seems like we can only add one analytical label per message sent.

**Comment by a6wu** [comment]
Thanks @g9singh. Here's an option for the labels in the format of <Group>-<NotificationType>. Let's review and come up with other ideas.

BasicNeeds-FreeFood
Registrar-ClassRegistration
ISPO-DocumentUpdate
Campus-TestkitScan
Campus-TownHall

**Comment by g9singh** [comment]
The message payload will look like the following:
```
{
    "to": {
        "topics": ["campusAnnouncements"]
    },
    "body": {
        "title": "TEST 1",
        "message": "test 1",
        "fcm_options": {
            "analytics_label": "direct_test_label"
	}
    }
}
```
The new fcm_options attribute allows us to add a label to any notification sent using firebase.
The filter option on the notification dashboard (within the firebase console) allows us to have more accurate data.

![Screen Shot 2021-02-19 at 12.52.45 PM.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/6dfce7dd-00db-41dc-b32b-4ddf3d7673b6)

The next steps would be:
- [ ] update API documentation for the [MobilePlatform-Messages](https://api-qa.ucsd.edu/store/apis/info?name=MobilePlatform-Messages&version=1.0.0&provider=mcmuniz) API in qa. The api is pretty out of date and I was unable to modify the swagger file due to a missing dependency![Screen Shot 2021-02-19 at 1.32.22 PM.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/6242b3ae-2884-4855-8ce7-6cc873e2c6be)
- [ ] update source code [add-analytics-label](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/src?at=refs%2Fheads%2Fadd-analytics-label)
- [ ] merge changes from [add-analytics-label](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/src?at=refs%2Fheads%2Fadd-analytics-label) into [qa](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/src) 
- [ ] deploy messaging-center-trigger in [qa](https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/messaging-center-trigger?tab=configuration) to test
- [ ] integrate this payload change within any client/tool we use to send Push Notifications

**Comment by g9singh** [comment]
Tasks to prod:

- [ ] promote messaging-center-trigger lambda from qa
- [ ] update the APIM swagger file ([source code](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/swagger.YAML))
- [ ] merge [qa](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse/src) branch into [prod](https://sourcecode.ucsd.edu/projects/WTS/repos/mobileplatform-notificationmessages/browse?at=refs%2Fheads%2Fprod) branch

**Comment by kevdesilva01** [comment]
Testing Notes:

Notifications sent using Postman 

Notifications sent using analytics parameter
` "fcm_options": {
    "analytics_label": "Direct-Test"
 }`

To view analytics, go to https://console.firebase.google.com/u/0/project/uc-san-diego-qa/notification/reporting and filter with the corresponding analytics label.
