### ISSUE TITLE
iPad Scanner Native SDK

### ISSUE THREAD

**Issue by vesp56** [UCSD/campus-mobile#1157]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The iPad app implements the native Scandit SDK
- [x] Tested successfully on iPad (@c3bryant)

**Comment by asg003** [comment]
IPad app implements Scandit SDK, and is able to scan and submit barcodes while rejecting invalid barcodes. Currently isn't able to recognize duplicate barcodes.

**Comment by g9singh** [comment]
After testing the app more thoroughly using the following [smoke test](https://ucsdcloud.sharepoint.com/:x:/s/WorkplaceTechnologyServices-CampusMobileBuilds/EcA3lE6lkqZEhnzpxnk20zEB_-SJtRc0beA3D6mGhXDnzg?e=SJWJfc) we have found few issues.

When a staff member successfully suits a scan the scanner still displays MyStudentChart instead of MyUCSDChart
![missing-staff-submission-text.PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/cdcb0e8b-3beb-4694-97f2-1ee5405d00e2)

When the user logs in and scans a barcode successfully the app logs the user out by navigating back to the login screen. However, if you look at the screen it has a back navigator on the top left. 
![auto-logout-navigation-issue.PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/43b4bcc4-da5d-41d5-97d6-61da2ec24e2a)

Once you tap that screen it takes you back to the scanner even though the user is logged out.
![result-of-auto-logout-failure.PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/fd94a1d9-70cb-4cf5-932d-6c62b3539c03)

If the user taps back one more time the app will redirect you back to the original login screen with the user's credentials already inputted into the fields.
![navigate-back-to-login .PNG](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/78a56490-cd57-417f-b97a-3942fca7b1b9)

This is not the expected behavior.
TODO:

- [ ] Make sure the auto logout navigates the user back to the login screen without having the back arrow
- [ ] Update the successful submission screen so that it reflects staff submission too (MyStudentChart and MyUCSDChart)

**Comment by g9singh** [comment]
Task was completed with this commit hash4423ae1d447ab777a18db0465137641e25c37c6b.
PR can be found [here](https://github.com/a6wu/mobile-qr-scanner/pull/39).
