### ISSUE TITLE
Detailed Marker Description

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1240]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-81

This is complete when:
- [x] The marker on the map search results displays detailed information. For example, COVID test kit location for Price Center should have the following information. "Faculty, staff and students can now pick up a self-administered asymptomatic COVID-19 testing kit via the vending machines. Wheelchair accessible (Ground level)."
- [x] [map-search-service](https://sourcecode.ucsd.edu/projects/WTS/repos/map-search-service/browse) updated to strip html tags from search result descriptions
- [x] HTML tags removed from map search results in QA
- [x] [PR 1256 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B663BFD4E-4E85-4AD5-AA15-E65D0866CBD7%7D&file=PR-1256-Test-Plan-7.6.0-QA-1277.xlsx&action=default&mobileredirect=true) PASS on iOS (c3bryant)
- [x] [PR 1256 Test Plan](https://ucsdcloud.sharepoint.com/:x:/r/sites/WorkplaceTechnologyServices-CampusMobileBuilds/_layouts/15/Doc.aspx?sourcedoc=%7B663BFD4E-4E85-4AD5-AA15-E65D0866CBD7%7D&file=PR-1256-Test-Plan-7.6.0-QA-1277.xlsx&action=default&mobileredirect=true) PASS on Android (asg003)
- [ ] [map-search-service](https://sourcecode.ucsd.edu/projects/WTS/repos/map-search-service/browse) deployed to PROD
- [ ] [map-search-service](https://sourcecode.ucsd.edu/projects/WTS/repos/map-search-service/browse) verified in PROD

<img src="https://images.zenhubusercontent.com/5a714b9f4b5806bc2bc4fcb0/81a9b9d2-e9c8-4b72-b8ae-65f05531a5ee" width="400">

**Comment by gmihir** [comment]
This is done in iOS (also seems to fix #837), but there are some issues on Android. 

iOS:
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-18 at 17.10.37.png](https://images.zenhubusercontent.com/5ecf51f81b04ffcb6094acce/645d1198-8bdf-43f4-af8f-5549eac398dd)

Android:
![Screen Shot 2021-02-18 at 5.13.36 PM.png](https://images.zenhubusercontent.com/5ecf51f81b04ffcb6094acce/f731593b-5ccc-4078-a203-e0c92ba6cf40)

The discrepancy in the way the InfoWindow on the Marker is shown is due to a difference in the Google Maps SDK for iOS and Android. This is not a Flutter issue and is an inconsistency with Google SDK's (https://github.com/flutter/flutter/issues/32145). Since the InfoWindow is not a Widget, we cannot modify how it works. There may be a way around this with this pub package (https://pub.dev/packages/custom_info_window), but this package is not very popular and may not be suitable.

**Comment by c3bryant** [comment]
Map search service ready to deploy to PROD.
Repo: https://sourcecode.ucsd.edu/projects/WTS/repos/map-search-service/browse
Branch: master

Steps:
Lambda:
1. npm install, zip, upload MapSearch:$LATEST (https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/MapSearch?tab=code)
2. Create MapSearch:v3 alias
3. Set Runtime to Node.js 12.x

API:
4. Update API Gateway /v2/map/search:GET -> MapSearch:v3 (https://us-west-2.console.aws.amazon.com/apigateway/home?region=us-west-2#/apis/xgu9qa7gx4/resources/61mxkd/methods/GET)
5. Deploy API Gateway prod stage
