### ISSUE TITLE
XD Design Code Export

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1304]
Time Tracking: MA-124

XD design export to code

@woznaut

**Comment by c3bryant** [comment]
Met with woznaut to discuss. Meeting set for 06/01/21 to test Adobe XD export and import capabilities.

**Comment by c3bryant** [comment]
After reviewing across multiple projects (PAH, NTPLLN), XD code export is best suited as a means of getting semi-navigable XD designs into the hands of a customer on a physical mobile device for UAT.

The XD generated code is unoptimized and uneditable, suffers from the same underlying problems as Dreamweaver which have existed for over a decade. For example, in every XD export we see excessive usage of 'pins', intrudoced by `adobe_xd`'s 'pins' class. Pins attempt to position and size every widget absolutely, relative to its parent widgets. This can result in a working, interactive prototype for a specific device being designed for, but does not support dynamic screen sizes. The lack of dynamic screen size support coupled with a foreign widget heirarchy which nests dozens of absolutely positioned pins, rather than using Flutter-best-practice widget heirarchy and Flutter- or community-designed widgets suited for specific layout or functional goals, resulting in unoptimized and uneditable code, is a blocker.
