### ISSUE TITLE
Onboarding screen button rendering theme incorrect

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#1315]
ITS-PRO: MA-95

Onboarding screen button rendering theme incorrect

This is done when:
- [x] Onboarding screen button rendering theme corrected

<img src="https://images.zenhubusercontent.com/5a7c89504b5806bc2bc62c34/1380aec8-483e-405e-8278-671b052c91cb" width="300">

**Comment by kevdesilva01** [comment]
This issue will be solved by changing the buttons from FixedButtons (Flutter 1) to ElevatedButtons (Flutter 2) since the Flutter 2 version of fixed buttons (called TextButtons) are different:

"The new button classes do not support a separate highlight color because it’s no longer part of the Material Design.
https://flutter.dev/docs/release/breaking-changes/buttons#migrating-buttons-with-custom-colors

Having a white highlight is no longer supported by TextButton![Screen Shot 2021-04-16 at 4.27.46 PM.png](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/c385141b-6f69-43da-aab3-97ea0f1145d1), which means we need to use elevated buttons with no elevation. 

This will be fixed along with #1322. 
How it looks with ElevatedButton:

![Screen Shot 2021-04-16 at 4.27.37 PM.png](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/4827d43f-6800-4a9b-906a-c01427d37573)![Screen Shot 2021-04-16 at 4.27.37 PM.png](https://images.zenhubusercontent.com/5ecea3a4678feb5d077d0216/a8640b00-f5ac-49e4-8196-d5b88a9d0d78)
