### ISSUE TITLE
Night Theme

### ISSUE THREAD

**Issue by ischeinkman** [UCSD/campus-mobile#143]
It would be nice to have the ability to switch between the current black-text-on-white-background mode to a white-text-on-black background mode, to reduce nighttime eyestrain.

**Comment by i8wu** [comment]
I love night themes, I'll try to check this out.

**Comment by ischeinkman** [comment]
Actually, would it be fine if I do this one? Seemed like a good beginner issue to work on.

**Comment by i8wu** [comment]
Go for it.

**Comment by i8wu** [comment]
@ischeinkman I can only assume you're having a hard time figuring out how to do the night theme because of the amount of colors we're using. We're starting to refactor and use a smaller set of colors located in styles/ColorConstants.js

Night theme will probably be a lot easier to implement after we finish refactoring. If you wanna help please feel free to submit a PR!

**Comment by ischeinkman** [comment]
@i8wu 
That was definitely a major hurdle. Thanks for the update!
Where would I be able to find the details of the refactor? I couldn't find an issue for it.

**Comment by i8wu** [comment]
Actually didn't put an issue in to track it, it's technically part of this though. https://github.com/UCSD/campus-mobile/issues/146

**Comment by i8wu** [comment]
https://github.com/UCSD/campus-mobile/issues/177 I'm going to start working on this, lmk if you want to help.

**Comment by c3bryant** [comment]
Jeremy, can you help us with some mockups to show what a good end result for this would be before we proceed further?

**Comment by c3bryant** [comment]
This issue has been moved to our internal feature request board and will be re-opened should it become active again.
