### ISSUE TITLE
Card Management Grey Screen

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1499]
Time Tracking: https://its-pro.ucsd.edu/browse/MA-34

User report:
> Every time when I want to open ‘cards’ in ‘Profile’, the page will became grey( like loading picture or something) and the app stop working.
> Mobile App > Profile > Cards

This is done when:
- [x] Add try/catch around the Card Management build method which sends a Firebase crash report
- [x] Card Management view in Profile tab becoming grey reproduced on `experimental` branch
  - Issue occurs when the user is offline or the DefaultCards API is unavailable
    - 1. Install from app/play store
    - 2. Turn off internet access (i.e. Airplane mode)
    - 3. Load the app, login as Visitor
    - 4. Manage Cards screen grey
- [x] Card Management screen displays a message to the user when an error is caught

- [x] [PR 1712 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1712-Test-Plan-7.14.0-QA-1954.xlsx?web=1) PASS on iOS
- [x] [PR 1712 Test Plan](https://ucsdcloud.sharepoint.com/sites/WorkplaceTechnologyServices-CampusMobileBuilds/Shared%20Documents/Campus%20Mobile%20Builds/Pull%20Request%20Testing/PR-1712-Test-Plan-7.14.0-QA-1955.xlsx?web=1) PASS on Android

**Comment by xxwwyytt1** [comment]
1. I couldn't reproduce the issue. When trying, I did:

- Go into Cards page with student account/employee account/visitor
- Turn off cards on the Cards page and then turn on with one card at a time
- Turn off cards on the Cards page and then turn on with all cards
- Turn off cards on the Cards page, log out, then log back in (one card at a time/all cards)
- Starting with student account, turn off cards on the Cards page, log out, then log back in with employee account (one card at a time/all cards)
2. added try/catch block for crash reports in lib/ui/profile/cards.dart, `List<Widget> createList(BuildContext context)` method. The try/catch catches the error in the process of rendering each ListTile in the Cards page, and replaces the tile with a temporary title with plain text "error".
3. still having trouble figuring out what the issue would be because of failure to reproduce the issue.

**Comment by p8gonzal** [comment]
To confirm, rather than a grey screen, we want to allow card reordering? Or will it simply say card management unavailable? @c3bryant

**Comment by c3bryant** [comment]
Hi @p8gonzal,
In the case where the app user or remote profile API are offline, ideally the user would be able to see and manage (reorder/hide/show) their local cards. The Manage Cards screen seems dependent on the remote cards API, which is not ideal.

**Comment by p8gonzal** [comment]
Note that offline card reordering is no longer necessary. A message to the user when entering the Card Management screen is all that is necessary.

**Comment by p8gonzal** [comment]
Issues encountered during Android testing.

**Comment by keskinmbaha** [comment]
I found a possible bug that is related to this issue. When encountering it it throws this error:

>'All children of this widget must have a key'

1. Log into UCSD App with Student or Staff account
2. Remove the app from memory
3. Before everything can fully load in, go to 'Profile' page and click on 'Cards'
4. You will see all the default cards lists will display, then as the app is fetching the profile, it will throw the error and change the list to include staff or student cards

Below is a video in QA, but this issue happens in Prod as well.

https://user-images.githubusercontent.com/62824264/147006874-5e16d992-84f1-4108-bedb-df7e492ca566.mov
