### ISSUE TITLE
Card Management Online/Offline Status Does Not Change

### ISSUE THREAD

**Issue by keskinmbaha** [UCSD/campus-mobile#1749]
Time Tracking: MA-78

When a user opens the app and they are online, but while using the app they go offline, the 'Card' page on the 'Profile' page does not display/indicate that the user is offline. If the user opens the app while offline and then comes back online, the 'Card' page still says the user is offline.

This is done when:
- [ ] Card Management online/offline status updates as expected based on your network connectivity

**Comment by xxwwyytt1** [comment]
Implemented with Internet connectivity listening. 
[Testing demo video](https://drive.google.com/file/d/1uT-aG872VqxILv4GlAIBWi8wpIrPdJ4-/view?usp=sharing) while connected to my phone

**Comment by xxwwyytt1** [comment]
Implemented with the connectivity package and added a Internet connectivity provider so that it could potentially be used in other offline related issues. Current demo: [https://drive.google.com/file/d/1MfdrtI8m3OJ2Wt6vo4COjzNcuPiWIeR1/view?usp=sharing](https://drive.google.com/file/d/1MfdrtI8m3OJ2Wt6vo4COjzNcuPiWIeR1/view?usp=sharing)

**Comment by tkiyohar** [comment]
Significant errors encountered while testing on Android. Please see my testing report for more information.

**Comment by c3bryant** [comment]
The effort to address this enhancement has outweighed the benefit. Closing to revisit at a later date.
