### ISSUE TITLE
Mock Enhanced Messages View

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#1763]
Time tracking: https://its-pro.ucsd.edu/browse/MA-42

This is complete when: 
- [x] A UI mockup shows how categories might work in the messages view
- [x] A UI mockup for other improvements

**Comment by sramcode** [comment]
initial mockup: https://www.figma.com/file/Q5YxK1vo2JAWvXRUFDH8HK/Notifications?node-id=0%3A1

**Comment by sramcode** [comment]
demo video: https://images.zenhubusercontent.com/62921972/64346715-464b-4fc9-92fe-30b138886ed9/notification_demo.mp4

**Comment by a6wu** [comment]
@woznaut Comments on the demo video?

**Comment by woznaut** [comment]
1. in the Notifications list view the icons are over-emphasized. I'd recommend making them the same as what's in the filter view - same size, line-weight, get rid of the grey circle background
2. the blue "unread" indicator is too crowded where it is - if you look at the Filter view, notice that everything is correctly left-aligned and maintains the proper space between the edge of the screen and the on-screen element. a better solution might be to put the indicator top right of the icon same as the icon in the bottom nav
3. the "pinned" indicator should be top right of the icon rather than bottom right - replacing the "unread" indicator. that would make all the indicator placements consistent throughout
