### ISSUE TITLE
Dining V2 Update

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#201]
At a high level, this task is to:
- Upgrade the current dining feed to the HDH V2 API
- Update the app UI to reflect all cosmetic and content related changes in this issue

HDH V2 API for Dining Information
http://hdh2.ucsd.edu/diningmenu/api/DiningDataService/GetDiningInfo_V2

HDH V2 API for Menu Information
http://hdh2.ucsd.edu/diningmenu/api/DiningDataService/GetDiningInfo_V2/64
- A call made for menu information should only be made upon the loading of the DiningDetail view
- Save the result of each request to the store with a TTL of 1 day

**Comment by c3bryant** [comment]
As part of the dining feed V2 update, also incorporate the following:
- Add disclaimer message provided by HDH
- Add allergen message provided by HDH
- Add payment options to the dining list and dining detail views

**Comment by Gulci** [comment]
Commit 98815c5 finalizes new logic behind the dining v2 redesign.

The front-facing home card now displays the current status of an eatery, with text denoting if the eatery is closing or opening soon.

![New Dining Card View](https://i.imgur.com/cQE2KgN.png)

The dining details view now dynamically displays hours based on the dining-v2 API from HDH.

![New Dining Detail View](https://i.imgur.com/cQE2KgN.png)

Ingredients and disclaimers are now displayed in the nutrition facts for menu items.

![New Nutrition Facts](https://i.imgur.com/CankbUv.png)

**Comment by c3bryant** [comment]
DiningService V2 has been added to AWS QA. The V2 API will now perform a clean merge of the HDH V2 and non-HDH(CMS) dining feeds, and return the result.

API Gateway:
https://zbncpgqqj4.execute-api.us-west-2.amazonaws.com/dev/v2/dining-service

Lambda:
https://us-west-2.console.aws.amazon.com/lambda/home?region=us-west-2#/functions/DiningService

Lambda Repo:
https://sourcecode.ucsd.edu/projects/WTS/repos/dining-service/compare/commits?sourceBranch=refs%2Fheads%2Fdining-v2&targetBranch=refs%2Fheads%2Fmaster

**Comment by Gulci** [comment]
A few changes have been made to restaurants with special hours in place.

We will no longer display a status for that eatery because it is not possible to display it with 100% certainty. Instead, a message is displayed indicating to the user that special hours may be in effect.

Additionally, if GPS coordinates are not available, the option to navigate is still offered. Instead of using coordinates, it uses any address data that an eatery may have associated with it. If none is available, then no walking icon / navigation option is displayed.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/8071536/38516951-45d9b888-3bed-11e8-9b3c-6279d9e343bb.png">

**Comment by c3bryant** [comment]
Verified and merged into v5.6-rc
