### ISSUE TITLE
Define Card Types

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#23]
Define a set of guidelines for each of the card types:
- News
- Events
- Banner
- Emergency
- Yes/No

**Comment by i8wu** [comment]
I think card types should be defined on terms of functionality instead of category?

List Card (News, Events, Dining, Shuttle (kinda))
- Has header
- Has list of 3 items
- Has a view all button

Picture/Banner Card (Welcome week, emergency?)
- No header
- Single image
- onPress takes to view with more info

Yes/No Card
- No header
- Short question
- Dismissible
- Had yes/no buttons that dismiss card after selection

**Comment by c3bryant** [comment]
Guidelines have been defined, moving this to internal for further review
