### ISSUE TITLE
SSO: Implement new authorization request method

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#251]
Implement the new authorization request method flow as described here: [App Handling of General SSO](https://www.lucidchart.com/documents/edit/adacf142-4e65-4e71-88d0-d5210632dfea?shared=true&)

**Comment by Gulci** [comment]
Commit 017968c and 823c49d introduce a new flow for making an authorized request. Now, we will assume the stored access token is correct. If a 401 Unauthorized response is received, the app will automatically attempt to refresh the token and then repeat the failed request. It will retry a predetermined amount of times at a preset interval (set in `AppSettings.js`). If it fails and exceeds the max retries that have been allotted to it, it will put the app in an error state in which no more auto-refreshing will occur, and no authenticated requests will succeed.

**Comment by Gulci** [comment]
Commit 57a23a2 introduces "Panic Log Out" which will log the user out of the app completely. This is for the cases where, for example, a user changes their password and the app tries to re-authenticate automatically with the old password.

**Comment by Gulci** [comment]
@a6wu, @c3bryant, We need to implement / decide on the errors and feedback we want to display to the user in the following situations:
1) User has been logged out because of an IDP / invalid stored credentials error
2) App was not able to re-authenticate due to some other error (timeout, airplane mode)

Things to consider:
Should we display a little warning triangle next to a card that can't update? 
<img width="27" alt="image" src="https://user-images.githubusercontent.com/8071536/39782585-6f8a7fa0-52c7-11e8-8df7-75777f14e9e0.png">

If we weren't able to re-authenticate, should we make them log in by typing their password again? Or should we just "remember" their password and let them click a "reauthenticate" button?

**Comment by Gulci** [comment]
Commit 9af5b86 has added functionality that alerts the user if they have been forced to log out if their password changed or their stored credentials are invalid.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/8071536/39899742-7aa09666-5472-11e8-83fb-1c045c98258e.png">

![image](https://user-images.githubusercontent.com/8071536/39899759-957ac3b2-5472-11e8-9fc2-d61bfe7a5a11.png)

**Comment by Gulci** [comment]
Commit 265b68b adds warning indicators to cards if there seem to be errors syncing data.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/8071536/39900658-22aa8c68-5478-11e8-8f99-478367e03998.png">

**Comment by Gulci** [comment]
0193835 adds functionality that alerts the user if they are using an outdated version of the app.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/8071536/39947037-57bef3fa-5525-11e8-8ce1-b455ef463472.png">

**Comment by c3bryant** [comment]
Verified in v6.0-rc, closing
