### ISSUE TITLE
Include Email from Login in Feedback Form

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#319]
When the user is logged in, do not prompt the user for an email in the feedback form. Use the email associated with the logged in account.

**Comment by c3bryant** [comment]
There are three cases to consider:
1. Per Allan not all User ID's are tied to an email address
2. Feedback submitted via the app can currently be anonymous. Would the user have to log out in order to submit the form anonymously?
3. The user may want to enter a different email address than that tied to their AD User ID, like a gmail account for example. Would we want to provide a way to the user override their AD email address?

@a6wu @woznaut sending this your way for review

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
