### ISSUE TITLE
Null is not an object (evaluating 'p[o.id]')

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#482]
### Issue Description

Bugsnag reported the following unhandled error:
```TypeError: null is not an object (evaluating 'p[o.id]')```

### Additional Info
* [Bugsnag report](https://app.bugsnag.com/ucsd/ucsd/errors/5cc5fad8ef076b0019d0b6d1?event_id=5cc5fad80038c5e2eac70000&i=sk&m=nw)
* React Native version: All
* Platform(s) (iOS, Android, or both?): both

**Comment by a6wu** [comment]
Step 1. Fix crash
Step 2. Resolve root cause

**Comment by sssaiya** [comment]
After recreating, Seems that duplicate keys are being passed in
![image.png](https://images.zenhubusercontent.com/5c479bf58d88074ab2c6a60f/9d3edadc-d557-412e-9d84-3e1d0be2d7ed)

**Comment by sssaiya** [comment]
This is happening because the closest stop may also be a stop that the user has added manually, 
In this case closest stop is Torrey Pines and I have added Torrey Pines
Gagan was trying to recreate this from home and wasn't able to as the closest stop was not something he had added.
![image.png](https://images.zenhubusercontent.com/5c479bf58d88074ab2c6a60f/dea3b8b0-f44b-45ff-be5d-3b6ac8c55da4)

**Comment by sssaiya** [comment]
completed in commit [8d9aa13](https://github.com/UCSD/campus-mobile/commit/8d9aa13f06aa775cf24186b5fee461630a447278)

**Comment by c3bryant** [comment]
Test results:
PASS on iOS, no issues found
PASS on Android, no issues found

Merged into 6.7
