### ISSUE TITLE
Add Badge Icon Indicator

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#491]
Add badge icon indicator to the app logo image on the OS home screen. The indicator will have a number to indicate the number of unread messages.

![Image from iOS.png](https://images.zenhubusercontent.com/5b7c4f70c76bd14ae4d85c98/87364d3f-d0c8-4394-8b1d-010bf82c99f6)

**Comment by sssaiya** [comment]
_On Android, seems we can only add a badge but cannot put a number in the badge._
![image.png](https://images.zenhubusercontent.com/5c479bf58d88074ab2c6a60f/55b221c2-5b39-4148-a451-9eb366ebce9c)

[https://stackoverflow.com/questions/17565307/how-to-display-count-of-notifications-in-app-launcher-icon?noredirect=1&lq=1](https://stackoverflow.com/questions/17565307/how-to-display-count-of-notifications-in-app-launcher-icon?noredirect=1&lq=1)

**Comment by sssaiya** [comment]
Made progress in commit [5841678](https://github.com/UCSD/campus-mobile/commit/5841678cb0cd71839985d90d73455cb387110236)

@g9singh Would like your help in testing since it requires receiving notifications.

**Comment by g9singh** [comment]
Extra notes: During initial implementation I ran into some issues running the badge indicator icon on android. 

The firebase library used to set badge icon in react native uses a library to set the indicator on android. However this library is only compatible with certain devices.

Knowing this we would like to move forward with the implementation by having an if check before we make the call to set badge icons just to see if the device is android or iOS. If it is iOS then we can make the call to set the badge number, otherwise do nothing. 

These links may help: 
https://github.com/leolin310148/ShortcutBadger
https://rnfirebase.io/docs/v3.3.x/messaging/reference/messaging

**Comment by vishant101** [comment]
Reading issues for react-native-firebase:

https://github.com/invertase/react-native-firebase/issues/2076
https://github.com/invertase/react-native-firebase/issues/1945
https://github.com/invertase/react-native-firebase/issues/2141

It's fairly apparent that the badge support on Android is not very robust and prone to discrepancies in performance based on the device/os. Should we limit the badge icon indicator to just iOS moving forward?

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
