### ISSUE TITLE
Parking: Spot Type Service

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#497]
This task is to create a Spot Type service. This will allow spot types to be updated dynamically and remotely for all campus mobile users.

Static JSON: `app/views/parking/ParkingSpotTypeList.json`

New Remote JSON: https://ucsd-its-wts-dev.s3-us-west-1.amazonaws.com/parking/ParkingSpotTypeList.json
Bucket: `ucsd-its-wts-dev`

Look into using an event-based approach, i.e. when AppState changes to `active`

**Comment by vishant101** [comment]
I've completed the service on 0227b2f505bf77e57a8c5d46140be15bc794e08a and deployed it to dev on AWS lambda.

@c3bryant @g9singh  Please test and let me know if any changes are required.

**Comment by g9singh** [comment]
@vishant101 Great job on the first part of the task! The remainder of the task is to add code to the client side that will pull the data generated by the service we have just created. Also look into using an event based approach while completing this task.

**Comment by vishant101** [comment]
Completed using a TTL on db74c2057716b2613a5f93f79c95eb6833271683

Know issues: 

The dev endpoint setup to return parking lot information at https://4pefyt8qv7.execute-api.us-west-2.amazonaws.com/dev/parking/v1.1/parking-spot-types returns SIO as a parking type. The app does not have logic to handle this as it's currently part of ticket #496. The app however renders SIO 
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/ba74a131-bdbf-4777-8efb-23cf93384b6b)

It is available to be selected however does not show up on the parking card on the main screen. 

@c3bryant @g9singh  maybe we should consider reworking the parking spot logic to remove all internal references to the spot types so that any changes to the data from the endpoint i.e. a new spot type automatically work without any additional client work needed.

**Comment by vishant101** [comment]
Update: #496 was updated to rework the parking logic to work with dynamically work with data from the end point.

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
