### ISSUE TITLE
Google Maps not loading in debug mode

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#531]
### Issue Description
In debug mode while developing for Android, Google Maps is failing to load on the Maps tab and the Shuttle Stop view. The map renders as just a grey background with a Google logo in the bottom corner. Investigate and fix.

### Additional Information
* Environment: Debug
* Platform(s) (iOS, Android, or both?): Android

**Comment by vishant101** [comment]
## Issue
![image.png](https://images.zenhubusercontent.com/5c533c9683ccb62a1a08b582/71bea86c-afb7-464c-a136-ce303728b5fe)

Per the Image above, maps do not load on android.  This occurs on the android emulator and cell phones for both QAT and PROD builds that are not final release APKs. This problem is widely associated with invalid keys.  Checking for the validity of our map key revealed that our key was valid, however, it is restricted to only work on release builds (meaning final release APKs).

## Solutions
### Add Debug Hash
Within the key management portal we can add the key-store hash for the debug version of the app.  The debug key-store is different for every developer and every environment. This means for every environment a new hash will have to be generated and added to the list of  acceptable keys. 

### Create a new API key for Debug Instances
A new unrestricted map API key could be created and used for debug versions of the app. 

@c3bryant @a6wu

**Comment by c3bryant** [comment]
Thanks @vishant101 - we will add developers to the existing key as needed for the time being
