### ISSUE TITLE
Availability: Card shows up with an error on initial launch

### ISSUE THREAD

**Issue by c3bryant** [UCSD/campus-mobile#557]
### Issue Description
Card shows up with an error on initial launch. Investigate and fix
![IMG_0063](https://user-images.githubusercontent.com/15112294/63535933-7a3f1000-c4c7-11e9-9fa5-10981096f670.PNG)

### Additional Information
* App Version: 6.8. 6.9

**Comment by g9singh** [comment]
This issue is related to the following bug caught by Bugsnag on build 686. This build was testing the react-native-60 branch.

https://app.bugsnag.com/ucsd/ucsd/errors/5d5c2b53db396f001bd829ed?filters[release.seen_in][0][type]=eq&filters[release.seen_in][0][value]=6.9%20(686)

The root cause of the issue was a breaking change* in the react-native upgrade. The delay function was moved out of redux-saga/ and placed in redux-saga/effects. So I simply updated the import statement to reflect the change.

commit: 3138b62a3d88dfb46c301c32227ea1b981dd6a1f
Verified on android and iOS simulators from the feature/react-native-60 branch

Next step would be to test on device 

(*) more info on the breaking change:
https://github.com/redux-saga/redux-saga/blob/master/CHANGELOG.md

**Comment by c3bryant** [comment]
This issue is being closed due to platform migration and may be revisited at a later date.
