### ISSUE TITLE
Surf Report Feed Alternative

### ISSUE THREAD

**Issue by i8wu** [UCSD/campus-mobile#65]
Surf Report currently relies on http://feeds.feedburner.com/surfline/Xqya
FeedBurner seems to be reaching EOL, so it may be smart to move onto something else.

http://magicseaweed.com/developer/forecast-api has been identified as a promising alternative.
*MSW use will require a "Powered by" logo http://magicseaweed.com/developer/terms-and-conditions

**Comment by i8wu** [comment]
Emailed some people on the UCSD surf team to see if this would actually be useful.

**Comment by i8wu** [comment]
Response:
Live wind and tide are needed at the very least. 
Access to at least the public cameras that are free streaming would also be very enticing to users.

**Comment by a6wu** [comment]
Review if this is viable, http://api.surfline.com/v1/forecasts/4812?resources=surf&days=3&getAllSpots=false&units=e&interpolate=false&showOptimal=true&callback=

**Comment by c3bryant** [comment]
Move to internal list for further review

**Comment by c3bryant** [comment]
Progress with MagicSeaweed stalled out. Let's move forward with the SurfLine v1 API

The SurfLine v1 API is lacking in documentation, but from what other users have said it is a fairly stable offering that has been in production for some time



API Overview:

Param | Values | Effect
----- | ------ | -------
spot_id | integer | Surfline spot id that you want data for. A typical Surfline URL is http://www.surfline.com/surf-report/torrey-pines-state-beach-s-southern-california_107951/ where 107951 is the spot_id. You can also get this from the response's id property.
resources | string | Any comma-separated list of "surf,analysis,wind,weather,tide,sort". There could be more available that I haven't discovered. "Sort" gives an array of swells, periods & heights that are used for the tables on spot forecast pages.
days | integer | Number of days of forecast to get. This seems to cap out at 16 for Wind and 25 for Surf.
getAllSpots | boolean | false returns an object containing the single spot you requested, true returns an array of data for all spots in the same region as your spot, in this case "South San Diego"
units | string | e returns American units (ft/mi), m uses metric
usenearshore | boolean | The best that I can gather, you want this set to true to use the more accurate nearshore models that take into account how each spot's unique bathymetry affects the incoming swells.
interpolate | boolean | Provide "forecasts" every 3 hours instead of ever 6. These interpolations seem to be simple averages of the values of the 6-hour forecasts.
showOptimal | boolean | Includes arrays of 0's & 1's indicating whether each wind & swell forecast is optimal for this spot or not. Unfortunately the optimal swell data is only provided if you include the "sort" resource - it is not included in the "surf" resource.
callback | string | jsonp callback function name

**Comment by c3bryant** [comment]
Hi Vivian, this is a before and after of the changes we are looking to achieve during the feed migration.

The new API endpoint we will use is: http://api.surfline.com/v1/forecasts/107951?resources=surf,analysis&days=1
The old endpoint is: https://s3-us-west-2.amazonaws.com/ucsd-its-wts/now_ucsandiego/v1/surffeed.json

Here is one entry from the current surffeed.json:

```
[
	{
		"date": "Thu, 26 Oct 2017 07:02:45",
		"link": "http://www.surfline.com/rss/rssredirect.cfm?id=4249",
		"description": "Another beautiful morning of brisk offshore flow and smooth conditions.&nbsp;Easing South and NW swell, while SW pulse continues for mainly waist-shoulder+ high waves.",
		"title": "BIRDROCK : 3-4 ft. + - waist to shoulder high and fair to good "
	},
	{
		...next beach
	}
]
```


For the new feed, incorporating a few changes will eliminate some parsing still done in the app. The ideal format after the migration would be this:

```
[
	{
		"date": "2017-10-26T17:54:58Z", // ISO 8601 timestamp (https://en.wikipedia.org/wiki/ISO_8601)
		"title": "BIRDROCK",
		"description": "Another beautiful morning of brisk offshore flow and smooth conditions.&nbsp;Easing South and NW swell, while SW pulse continues for mainly waist-shoulder+ high waves.",
		"surf_max": "8",
		"surf_min": "5"
	},
	{
		...next beach
	}
]
```

**Comment by vvp002** [comment]
Update to format: 
- Moved Date to top of the report
- Split forecast into separate reports (short-term and time based report)
- 1 column list of beach spots and surf level

![image](https://user-images.githubusercontent.com/13816146/33729329-1f028b98-db32-11e7-9937-9d0d68540845.png)

**Comment by c3bryant** [comment]
Deployed in 5.5
