### ISSUE TITLE
Bug: Scan View Freezes

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#658]
Campus mobile app, scan feature.

For every scan, need to go to previous page and come back and scan again

**Comment by g9singh** [comment]
I can only reproduce this behavior on iPhone devices running build 51 from test flight. 
Steps to reproduce:
Open app and log in
Go to scanner view
While in scanner view exit app (without closing fully)
Resume application and see that camera is frozen

Notes: 
When camera freezes user is still able to submit text that was previously on screen. 
User has to navigate back to the home screen and then re-enter the scan view in order to scan another code.
The app can scan multiple codes without having to navigate back to the home screen if the freezing does not occur.

**Comment by g9singh** [comment]
can not reproduce on latest build in experimental-v2 branch

**Comment by a6wu** [comment]
Cannot reproduce
