### ISSUE TITLE
Parking Card

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#771]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-84

### Issue Description

Implement parking card into the home view.

This is done when:

- [x] Parking card displays on the home view
- [x] User can toggle on/off the card in the Settings view
- [x] User can filter out by permit types
- [x] User can hide the card from the card setting
- [x] User can select which lots to display (manage lots)
- [x] User can reorder the parking lots (manage lots)
- [x] User lot and permit type preferences are saved on app exit

**Comment by sssaiya** [comment]
Completed in #901 
Further steps needed :
- Move historic data to database for quicker querying
- Cache responses, or make all page requests at once
- Left right scroll issue (Sometimes the card gets stuck mid scroll)
- It should be possible to move the controller for left and right scroll to the webpage itself. Instead of making multiple requests every time we navigate to a new card, we should make one request for all the data, making scrolling much smoother.
