### ISSUE TITLE
Remove Refresh Token Code

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#831]
Time Tracking: MA-95

This is done when:
- [x] Refresh token code has been removed from the app
- [ ] Tested successfully on iOS (@kevdesilva01)
- [ ] Tested successfully on Android (@kevdesilva01)

**Comment by c3bryant** [comment]
Completed in #1152

**Comment by kevdesilva01** [comment]
This issue is also linked to PR #1152, changes in the PR are confirmed but there is a merge conflict with experimental that will require updates to the PR to be able to merge. 

`lib/ui/common/webview_container.dart:210:35: Error: The method 'refreshToken' isn't defined for the class 'UserDataProvider'.
 - 'UserDataProvider' is from 'package:campus_mobile_experimental/core/providers/user.dart' ('lib/core/providers/user.dart').
Try correcting the name to the name of an existing method, or defining a method named 'refreshToken'.
          await _userDataProvider.refreshToken();
                                  ^^^^^^^^^^^^`

**Comment by a6wu** [comment]
Added to #1141
