### ISSUE TITLE
Parking office labels in Availability card could be mistaken for parking lots

### ISSUE THREAD

**Issue by woznaut** [UCSD/campus-mobile#847]
The labels for Parking Offices in the Availability card could make them easily mistaken for parking lots. one possible solution could be to append the labels with the work "Office" but only for the parking offices. other ideas?

![AvailabilityCardLabels](https://user-images.githubusercontent.com/19195410/88087464-ce220100-cb3d-11ea-856b-4422233da379.png)

**Comment by c3bryant** [comment]
I agree with your suggestion @woznaut that adding " Office" at the end of each parking office location would provide more context to users and help to avoid confusion.

Since this issue was added, the Occuspace API upgrade to V2 has been completed.
The vendor informed us a while back that they can make these changes on their end for V2 (unlike V1, which they could not).
 I would recommend formalizing this request with the vendor, to avoid incurring any unnecessary technical debt on our end.
