### ISSUE TITLE
Events Feed RSS to JSON

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#914]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-101

This is complete when:

- [x] The tockify RSS feed is converted into a JSON format for the mobile app
- [x] The event card displays the list of events
- [x] The detail vew of each event displays

**Comment by Atreto76** [comment]
I've created a rough implementation for this on [my repo](https://github.com/Atreto76/campus-mobile/tree/feature/rss-to-json-events).
There are several issues I have encountered:

1. XML dependency version difference
The flutter_test dev dependency has a dependency for an older version of the [xml package](https://pub.dev/packages/xml). This causes a version solving error as a new package I introduced, [xml2Json](https://pub.dev/packages/xml2json), relies on a newer version of the [xml package](https://pub.dev/packages/xml). I've removed flutter_test for now.

2. Some content provided by the RSS feed are causing issues
There are seemingly random backslashes in some parts of the contents returned from the RSS feed. They are causing format exceptions. All event information will not show up in the app until these are caught individually on a per-event basis.

3. Not everything that we had before is here
Unless I'm missing where they're at, a few things are missing that we previously had. Notably the link for the 'Learn More' button is missing. Instead a link to the Tockify event is given, and that page has the link to learn more.

4. Extraneous info
There's a lot of extra info given that isn't relevant. It was kept due to the conversion method used for XML to JSON. It's probably possible to get rid of it and clean up the events_model file but for now you'll have to sift through it.
