### ISSUE TITLE
Static WebCard Template

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#951]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-66

This is complete when:

- [x] A WebCard template with Title, Content, Menu Items is implemented
- [x] A new WebCard can be defined in the default card list and rolled out to the mobile app without a mobile app update to the Store
- [x] The WebCard HTML will live in the CMS https://mobile.ucsd.edu/replatform/v1/qa
- [x] PR 1132 Test Plan PASS on iOS
- [x] PR 1132 Test Plan PASS on Android

**Comment by lukedutta9** [comment]
Updated default cards to v3

Staff - [https://mobile.ucsd.edu/replatform/v1/qa/cards/staff_cards-v3.json](https://mobile.ucsd.edu/replatform/v1/qa/cards/staff_cards-v3.json)
Student - [https://mobile.ucsd.edu/replatform/v1/qa/cards/student_cards-v3.json](https://mobile.ucsd.edu/replatform/v1/qa/cards/student_cards-v3.json)
Visitor - [https://mobile.ucsd.edu/replatform/v1/qa/cards/visitor_cards-v3.json](https://mobile.ucsd.edu/replatform/v1/qa/cards/visitor_cards-v3.json)

**Comment by lukedutta9** [comment]
Default Cards v3 now updated with new attribute, requireAuth for auth cards.

**Comment by lukedutta9** [comment]
Submitted PR #1132 for this issue, issue title should be changed back to "WebCard Template" because PR now supports auth cards.

**Comment by g9singh** [comment]
@lukedutta9 Great job on the PR. Even though both builds passed the smoke test this PR can not be pulled in yet because it does not fulfill one requirement.
In the **lib/ui/home.dart** you reference code from the app constants file. This reference means that an update to the source code will be required any time we would like to deploy a new web card. 

Please see the following comment for more info: https://github.com/UCSD/campus-mobile/pull/1132/files#r543683751

**Comment by lukedutta9** [comment]
Currently working on refactoring the code so that the titles for the web cards do not rely on the CardTitleConstants. Will need to change CardsModels, update each affiliation's default cards list (v3), and refactor part of home.dart, where the cards are inserted.

For now, I'm just adding an extra element to each item in the default cards list, but in the future it would be better to have a separate resource that holds all the titles for each card.
