### ISSUE TITLE
Native Scandit SDK Integration

### ISSUE THREAD

**Issue by a6wu** [UCSD/campus-mobile#997]
ITS-Pro time category: https://its-pro.ucsd.edu/browse/MA-74

This is complete when:

- [x] The scanner is using the native Scandit SDK
- [x] The scanning UI and flow matches the current implementation
- [x] #1068

**Comment by gmihir** [comment]
https://pub.dev/packages/flutter_scandit_plugin

**Comment by gmihir** [comment]
Current progress with campus-mobile: https://github.com/gmihir/campus-mobile/tree/scandit-native-integration

Current progress with plugin: https://github.com/gmihir/flutter_scandit

**Comment by i8wu** [comment]
Hey, I think the issue was that you were just using the wrong function.
 
https://github.com/gmihir/flutter_scandit/blob/master/android/src/main/java/com/ysampir/flutter_scandit_plugin/ScanditView.java#L136

Should be using setColorInvertedEnabled(true)
 
https://docs.scandit.com/data-capture-sdk/android/barcode-capture/api/symbology-settings.html#property-scandit.datacapture.barcode.SymbologySettings.IsColorInvertedEnabled
 
Changing that lets me build, but I don't have an api key so I can't test. 
Can someone try it and verify if that's what the issue was?

**Comment by gmihir** [comment]
Both iOS and Android are now building with the modification, everything else is done for V1. Need an actual license key with the ucsd app identifier to test fully.
